
import S2507 from "./S2507.ts";
import { assertEquals } from "@std/assert";

const solution = new S2507();
const testinput = 
`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

Deno.test("Testinput first part", () => {
    assertEquals(solution.firstPart(testinput), 21);
});

Deno.test("Testinput second part", () => {
    assertEquals(solution.secondPart(testinput), 40);
});

